# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  imageRepo: hrapp
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
 
      inputs:
        containerRegistry: 'localhost:8080'
        repository: '$(imageRepo)'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          latest'

- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build 
  jobs:
    - job: Depoly
      displayName: Deploy to AKS
      pool:
        vmImage: ubuntu-latest
      steps:
        - 
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'mainifist'
          targetPath: '$(Pipeline.Workspace)/minifist'


       
