apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-d237"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-d237"
  template:
    metadata:
      labels:
        app: "myakscluster-d237"
    spec:
      containers:
        - name: "myakscluster-d237"
          image: "myaksclustername.azurecr.io/myakscluster"
          ports:
          - containerPort: 80